### ISSUE TITLE
TypeError: quote_from_bytes() expected bytes when using service.getMessages

### ISSUE THREAD

**Issue by nkovalevich** [feathersct/mirthpy#1]
When using service.getMessages('{channelID}') I'm getting the error "TypeError: quote_from_bytes() expected bytes"

full trace:

Traceback (most recent call last):
  File "C:\Users\(username)\PycharmProjects\MirthCheck\main.py", line 25, in <module>
    lastMessage = service.getMessages('{channelID}', limit=1, offset=0,startDate="none", endDate="none", status="none")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\(username)\PycharmProjects\MirthCheck\venv\Lib\site-packages\mirthpy\mirthService.py", line 777, in getMessages
    encParam = build_encoded_url_params(includeContent=includeContent, limit=limit, offset=offset, startDate=startDate, endDate=endDate, status=status)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\(username)\PycharmProjects\MirthCheck\venv\Lib\site-packages\mirthpy\utilities.py", line 25, in build_encoded_url_params
    params.append(key + "=" + urllib.parse.quote_plus(value))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\(username)\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 883, in quote_plus
    string = quote(string, safe + space, encoding, errors)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\(username)\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 867, in quote
    return quote_from_bytes(string, safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\(username)\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 897, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

**Comment by feathersct** [comment]
@nkovalevich sorry about the late response to this issue. The latest push should fix this. Thanks for spotting this. I'll push to pip soon.
